### ISSUE TITLE
Problems co-existing with ruby bundler

### ISSUE THREAD

**Issue by danroberts** [affinitybridge/git-bpf#9]
I have problems when git_bpf is installed in the same gemset as bundler, I get the error 

/Users/Infoactive/.rvm/gems/ruby-2.0.0-p353@global/gems/rubygems-bundler-1.4.2/lib/rubygems-bundler/noexec.rb:75:in `setup': undefined method`name' for #Array:0x1091f0810 (NoMethodError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `map'

I had both git_bpf and bundler installed in my global gemset, if I remove bundler, then git_bpf works. 

Any idea on how to make the two coexist?

**Comment by tnightingale** [comment]
I don't use rvm so haven't encountered this myself. @katbailey have you or anyone on your team run into this issue?

**Comment by danroberts** [comment]
It seems to be related possibly to the gemspec file missing some attributes bundler is expecting? 

Apologies if I am leading you down the wrong path, I don't fully understand this issue, but this is what some of my googling turned up:

https://github.com/bundler/bundler/issues/2615

**Comment by danroberts** [comment]
I resolved the issue. 

It seems to be related to the gem 'rubygems-bundler' which I had installed without knowing it.

https://github.com/mpapis/rubygems-bundler

Still not 100% sure why it was happening, but removing that gem solves the issue.
